### ISSUE TITLE
ctx not updated

### ISSUE THREAD

**Issue by vpistis** [aluxian/fish-kube-prompt#2]
Hi,

the context don't change after using `kctx -`.
I don't know if this is only a macos problem, I use fish `version 2.7.1`.

There is other init or configuration steps?

tx

**Comment by aluxian** [comment]
It should just work... this is probably because of the `stat` problem (the other issue you reported).

<img width="521" alt="screen shot 2018-03-24 at 15 22 20" src="https://user-images.githubusercontent.com/1418870/37865631-41dc727a-2f77-11e8-8ac9-bf1767df522f.png">


I need more info; did you change the scripts in any way?

**Comment by vpistis** [comment]
probably is due to the `stat` problem https://github.com/aluxian/fish-kube-prompt/issues/1

**Comment by aluxian** [comment]
This works now, right?

**Comment by vpistis** [comment]
yes! work like a charm! 👍
